# Generated by Django 4.0 on 2022-02-04 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0009_alter_profile_options_profile_person_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_slug', models.SlugField(allow_unicode=True, auto_created=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now=True, null=True)),
                ('publish_date', models.DateField()),
                ('is_allowed', models.BooleanField(default=False)),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='')),
                ('validityـduration', models.CharField(choices=[('1h', 'one houre'), ('1d', 'one day'), ('1w', 'one week'), ('1m', 'one mounth'), ('3m', 'three mounth'), ('6m', 'six mounth'), ('1y', 'one year'), ('al', 'always')], default='al', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.customer')),
            ],
        ),
    ]
