# Generated by Django 4.0 on 2022-02-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_slug', models.SlugField(allow_unicode=True, auto_created=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now=True, null=True)),
                ('publish_date', models.DateField()),
                ('is_allowed', models.BooleanField(default=False)),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='')),
                ('validityـduration', models.CharField(choices=[('1h', 'one houre'), ('1d', 'one day'), ('1w', 'one week'), ('1m', 'one mounth'), ('3m', 'three mounth'), ('6m', 'six mounth'), ('1y', 'one year'), ('al', 'always')], default='al', max_length=2)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('joined_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
