# Generated by Django 4.0 on 2022-01-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salesman', '0005_remove_salesmanprofile_is_salesman'),
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='salesman',
            field=models.ManyToManyField(to='Salesman.SalesmanProfile'),
        ),
    ]
