# Generated by Django 4.0 on 2022-02-04 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('News', '0001_initial'),
        ('Salesman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='salesman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Salesman.salesmanprofile'),
        ),
    ]
