# Generated by Django 4.0 on 2022-01-22 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Salesman', '0005_remove_salesmanprofile_is_salesman'),
        ('News', '0002_news_salesman'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='date',
        ),
        migrations.AddField(
            model_name='news',
            name='create_date',
            field=models.DateField(default='2012-05-09'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='is_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='validityـduration',
            field=models.CharField(choices=[('1h', 'one houre'), ('1d', 'one day'), ('1w', 'one week'), ('1m', 'one mounth'), ('3m', 'three mounth'), ('6m', 'six mounth'), ('1y', 'one year'), ('al', 'always')], default='1h', max_length=2),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='news',
            name='salesman',
        ),
        migrations.AddField(
            model_name='news',
            name='salesman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Salesman.salesmanprofile'),
        ),
    ]
