# Generated by Django 4.0.2 on 2022-02-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_alter_news_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribers',
            name='customer',
        ),
        migrations.AddField(
            model_name='subscribers',
            name='email',
            field=models.EmailField(default='m@b.com', max_length=254),
            preserve_default=False,
        ),
    ]
