# Generated by Django 4.0 on 2022-01-18 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Salesman', '0002_initial'),
        ('Product', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='salesman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesmen', to='Salesman.salesmanprofile'),
        ),
    ]
