# Generated by Django 4.0 on 2022-02-04 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_categorydetail_productdetails_wishlistdetail_and_more'),
        ('Salesman', '0001_initial'),
        ('User', '0009_alter_profile_options_profile_person_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='salesman',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='salesmen', to='Salesman.salesmanprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.profile'),
        ),
        migrations.AddField(
            model_name='productcomment',
            name='product',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Product.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Product.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='customer',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='User.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='category'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wishlistdetail',
            name='product',
            field=models.ManyToManyField(to='Product.Product'),
        ),
        migrations.AddField(
            model_name='wishlistdetail',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.wishlist'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='Product.product'),
        ),
        migrations.AddField(
            model_name='categorydetail',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_properties', to='Product.category'),
        ),
    ]
