# Generated by Django 4.0 on 2022-01-18 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
        ('Product', '0003_alter_category_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='User.profile'),
        ),
    ]
