# Generated by Django 4.0 on 2022-01-18 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_alter_product_salesman'),
        ('Product', '0004_alter_productcomment_author'),
    ]

    operations = [
    ]
