# Generated by Django 4.0 on 2022-01-23 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_remove_wishlist_product_wishlistdetail'),
        ('Product', '0005_merge_20220118_1538'),
    ]

    operations = [
    ]
