# Generated by Django 4.0 on 2022-01-10 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_remove_category_is_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='Product.category'),
        ),
    ]
