# Generated by Django 4.0 on 2022-01-25 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_merge_20220123_1257'),
    ]

    operations = [
    ]
