# Generated by Django 4.0 on 2022-01-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_alter_category_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='img',
            field=models.ImageField(null=True, upload_to='Product/img'),
        ),
    ]
