# Generated by Django 4.0 on 2022-01-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_productcomment_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(null=True, upload_to='Product/img'),
        ),
    ]
