# Generated by Django 4.0 on 2022-01-26 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_categorydetail_productdetail_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductDetail',
            new_name='ProductDetails',
        ),
    ]
