# Generated by Django 4.0 on 2022-01-26 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_merge_20220123_1251'),
        ('Product', '0009_rename_productdetail_productdetails'),
    ]

    operations = [
    ]
