# Generated by Django 4.0 on 2022-01-10 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomment',
            name='img',
        ),
    ]
