# Generated by Django 4.0 on 2022-02-02 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_remove_userdevice_check_field'),
        ('Product', '0010_merge_20220126_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.profile'),
        ),
    ]
