# Generated by Django 4.0 on 2022-01-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_category_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(null=True, upload_to='Product/image'),
        ),
    ]
