# Generated by Django 4.0 on 2022-01-20 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
        ('Payment', '0003_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.profile'),
        ),
    ]
