# Generated by Django 4.0 on 2022-01-27 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_merge_20220126_1621'),
        ('Payment', '0005_remove_wallet_owner_wallet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='create_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='holding',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='User.profile'),
        ),
    ]
