# Generated by Django 4.0 on 2022-01-27 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_merge_20220126_1621'),
        ('Payment', '0006_wallet_create_date_wallet_name_alter_wallet_holding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='User.profile'),
        ),
    ]
