# Generated by Django 4.0 on 2022-02-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0007_alter_wallet_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GateWaysModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.TextField()),
                ('payment_id', models.TextField()),
                ('amount', models.IntegerField()),
                ('date', models.TextField(default='-')),
                ('card_number', models.TextField(default='****')),
                ('idpay_track_id', models.IntegerField(default=0)),
                ('bank_track_id', models.TextField(default=0)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
