# Generated by Django 4.0 on 2022-02-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0008_gatewaysmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='holding',
            new_name='cash',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='name',
        ),
        migrations.AddField(
            model_name='wallet',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
