# Generated by Django 4.0 on 2022-02-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0009_rename_holding_wallet_cash_remove_wallet_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatewaysmodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
