# Generated by Django 4.0 on 2022-02-16 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesmanProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='User.profile')),
                ('validation_file', models.FileField(blank=True, null=True, upload_to='Salesman/validation_files')),
                ('isvalid', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=0, max_length=1)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('residenceـaddress', models.TextField()),
                ('shop_address', models.TextField()),
                ('shop_postal_code', models.CharField(max_length=10, null=True)),
                ('home_postal_code', models.CharField(max_length=10, null=True)),
                ('img', models.ImageField(null=True, upload_to='Salesman/profile')),
                ('shop_name', models.CharField(max_length=50, null=True)),
                ('shop_logo', models.ImageField(null=True, upload_to='shop_logo')),
            ],
            options={
                'verbose_name': 'Salesman',
                'verbose_name_plural': 'Salesmen',
            },
            bases=('User.profile',),
        ),
    ]
