# Generated by Django 4.0 on 2022-01-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=50, null=True)),
                ('shop_logo', models.ImageField(null=True, upload_to='shop_logo')),
            ],
        ),
    ]
