# Generated by Django 4.0 on 2022-02-04 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Salesman', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesmanprofile',
            old_name='rate',
            new_name='rating',
        ),
    ]
