# Generated by Django 4.0 on 2022-01-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_alter_product_salesman'),
        ('Salesman', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesmanprofile',
            old_name='postal_code',
            new_name='home_postal_code',
        ),
        migrations.RenameField(
            model_name='salesmanprofile',
            old_name='address',
            new_name='residenceـaddress',
        ),
        migrations.AddField(
            model_name='salesmanprofile',
            name='isvalid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesmanprofile',
            name='shop_logo',
            field=models.ImageField(null=True, upload_to='shop_logo'),
        ),
        migrations.AddField(
            model_name='salesmanprofile',
            name='shop_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesmanprofile',
            name='store_address',
            field=models.TextField(default='hh'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesmanprofile',
            name='store_postal_code',
            field=models.CharField(default=56565, max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Salesman',
        ),
    ]
