# Generated by Django 4.0 on 2022-01-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salesman', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesman',
            name='shop_logo',
            field=models.ImageField(null=True, upload_to='shop_logo'),
        ),
        migrations.AddField(
            model_name='salesman',
            name='shop_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesmanprofile',
            name='img',
            field=models.ImageField(null=True, upload_to='salseman/profile'),
        ),
        migrations.AlterField(
            model_name='salesmanprofile',
            name='rating',
            field=models.FloatField(default=0, max_length=1),
        ),
    ]
