# Generated by Django 4.0 on 2022-01-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salesman', '0003_rename_postal_code_salesmanprofile_home_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesmanprofile',
            name='is_salesman',
            field=models.BooleanField(default=True),
        ),
    ]
