# Generated by Django 4.0 on 2022-01-19 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Salesman', '0004_salesmanprofile_is_salesman'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesmanprofile',
            name='is_salesman',
        ),
    ]
