# Generated by Django 4.0 on 2022-02-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salesman', '0005_remove_salesmanprofile_is_salesman'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesmanprofile',
            options={'verbose_name': 'Salesman', 'verbose_name_plural': 'Salesmen'},
        ),
        migrations.RenameField(
            model_name='salesmanprofile',
            old_name='store_address',
            new_name='shop_address',
        ),
        migrations.RemoveField(
            model_name='salesmanprofile',
            name='store_postal_code',
        ),
        migrations.RemoveField(
            model_name='salesmanprofile',
            name='validation',
        ),
        migrations.AddField(
            model_name='salesmanprofile',
            name='shop_postal_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='salesmanprofile',
            name='validation_file',
            field=models.FileField(blank=True, null=True, upload_to='Salesman/validation_files'),
        ),
        migrations.AlterField(
            model_name='salesmanprofile',
            name='home_postal_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='salesmanprofile',
            name='img',
            field=models.ImageField(null=True, upload_to='Salesman/profile'),
        ),
    ]
