# Generated by Django 4.0 on 2022-01-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_salesman',
            field=models.BooleanField(default=False),
        ),
    ]
