# Generated by Django 4.0 on 2022-01-24 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_profile_is_salesman'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=256, null=True)),
                ('browser_type', models.CharField(max_length=256, null=True)),
                ('browser_version', models.CharField(max_length=256, null=True)),
                ('os_type', models.CharField(max_length=256, null=True)),
                ('os_version', models.CharField(max_length=256, null=True)),
                ('session', models.CharField(max_length=256, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='User.profile')),
            ],
        ),
    ]
