# Generated by Django 4.0 on 2022-01-26 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_admin_options_alter_customer_options_and_more'),
        ('User', '0004_rename_browser_type_userdevice_check_field_and_more'),
    ]

    operations = [
    ]
