# Generated by Django 4.0 on 2022-01-31 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_merge_20220126_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='last_login',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
