# Generated by Django 4.0 on 2022-02-02 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_userdevice_last_login'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userdevice',
            unique_together={('device_type', 'os_type', 'device_brand')},
        ),
    ]
