# Generated by Django 4.0 on 2022-02-02 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_userdevice_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdevice',
            name='check_field',
        ),
    ]
