# Generated by Django 4.0 on 2022-02-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_remove_userdevice_check_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
        migrations.AddField(
            model_name='profile',
            name='person_img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
    ]
