# Generated by Django 4.0 on 2022-02-14 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_alter_profile_options_profile_person_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='person_img',
        ),
    ]
