# Generated by Django 4.0 on 2022-02-15 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_remove_profile_person_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_salesman',
        ),
    ]
