# Generated by Django 4.0 on 2022-02-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_remove_profile_is_salesman'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_salesman',
            field=models.BooleanField(default=False),
        ),
    ]
